### ISSUE TITLE
Package installation fail on Apple M1 arm64

### ISSUE THREAD

**Issue by alexb2324** [Bioconductor/genefilter#5]
Currently experiencing package installation issues on Apple arm64 system. Installation issue addressed at the following link:

https://support.bioconductor.org/p/9138695/

The issue seems to have been temporarily resolved by another user. Was hoping to bring this issue to your attention so a patch can be implemented to resolve the issue. Thanks

**Comment by hpages** [comment]
As explained [here](https://support.bioconductor.org/p/9137290/#9137342), [here](https://support.bioconductor.org/p/9139482/#9139589), and in our [release announcement for BioC 3.14](https://bioconductor.org/news/bioc_3_14_release/), Bioconductor does not support Apple arm64 natively at the moment. The reason for this is that we don't have the resource and the hardware to produce, test, and distribute Mac arm64 binary packages yet.

Anyways the installation issue you're referring to was due to a misconfiguration on the user machine (gfortran was missing or not properly installed). So it's not an issue with **genefilter** itself (any R package with Fortran code would have failed to install), and the issue cannot be resolved with a patch to the package.

Cheers,
H.
